// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHXjB6TfDqlKdVYIKbfmHewGxk4UG7aXg',
    appId: '1:345248711660:web:8f7f7c9f4434435d4876c9',
    messagingSenderId: '345248711660',
    projectId: 'gestion-horas-complementarias',
    authDomain: 'gestion-horas-complementarias.firebaseapp.com',
    storageBucket: 'gestion-horas-complementarias.appspot.com',
    measurementId: 'G-FH16DLTZ1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_2UrP51VKlXBYZmAzKTpUx99D0hqXhtw',
    appId: '1:345248711660:android:8546569a4b765c0e4876c9',
    messagingSenderId: '345248711660',
    projectId: 'gestion-horas-complementarias',
    storageBucket: 'gestion-horas-complementarias.appspot.com',
  );
}
